use_frameworks!

target 'Longinus_Example' do
  platform :ios, '10.0'
  pod 'Longinus', :path => '../'

  target 'Longinus_Tests' do
    inherit! :search_paths

    
  end
end

target 'Longinus-SwiftUI-Example' do
  platform :ios, '13.0'
  pod 'Longinus/SwiftUI', :path => '../'
end
