name: build

on: [push, pull_request]

jobs:
  build:


    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 8']
        swift-version: [5.0]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        xcodebuild clean build -workspace Longinus.xcworkspace -scheme Longinus-Example -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env: 
        destination: ${{ matrix.destination }}
